### ISSUE TITLE
Current Errors I'm Getting with CL Calls

### ISSUE THREAD

**Issue by lwasser** [earthlab/grading-workflow-experiments#13]
Hey @betatim just wanted to document some of the issues i'm having with the CLI stuff.
I totally see how this is coming together. it's just not working for me quite yet so i'm hoping we can talk through this together today!!

- [x] ## Initialize Connection Returns: 422 Validation Failed
`nbinit`
I get failed validation for some reason. 
```
MacBook-Pro-4:autograded-course-starter leah-su$ nbinit
GitHub username: lwasser
Password for lwasser: 
Traceback (most recent call last):
  File "/Users/leah-su/anaconda3/bin/nbinit", line 11, in <module>
    sys.exit(init())
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/grading/__main__.py", line 56, in init
    two_factor_callback=two_factor)
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/github3/api.py", line 26, in deprecation_wrapper
    return func(*args, **kwargs)
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/github3/api.py", line 59, in authorize
    client_secret)
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/github3/github.py", line 462, in authorize
    json = self._json(self._post(url, data=data), 201)
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/github3/models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.UnprocessableEntity: 422 Validation Failed
```
- [x] ## Connect to Course

`nbdistribute --template`
note: this course i think exists but if it exists can it fail gracefully please?

```
MacBook-Pro-4:autograded-course-starter leah-su$ nbdistribute --template
Using /Users/leah-su/Documents/github/2-autograding/autograded-course-starter/student to create the student template.
Loading configuration from config.yml
Creating template repository.
Traceback (most recent call last):
  File "/Users/leah-su/anaconda3/bin/nbdistribute", line 11, in <module>
    sys.exit(distribute())
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/grading/__main__.py", line 131, in distribute
    config['github']['token'])
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/ruamel/yaml/comments.py", line 747, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'github'
```

## Setup student dir

`nbauthor --date 2018-01-01`
this works well so far! haven't tested working on a notebook yet. 

## Distribute assignment

This is still failing and i'm not sure why. 

```
MacBook-Pro-4:autograded-course-starter leah-su$ nbdistribute 
Using /Users/leah-su/Documents/github/2-autograding/autograded-course-starter/student to create the student template.
Loading configuration from config.yml
Fetching work for betatim...
Traceback (most recent call last):
  File "/Users/leah-su/anaconda3/bin/nbdistribute", line 11, in <module>
    sys.exit(distribute())
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/grading/__main__.py", line 144, in distribute
    token=config['github']['token'])
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/ruamel/yaml/comments.py", line 747, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'github'
```

## Creating student assignments
I am missing something here. i just made new assignments  but i only see one week1 folder in my student dir. 
```
MacBook-Pro-4:autograded-course-starter leah-su$ nbauthor --date 2018-12-01
Processing /Users/leah-su/Documents/github/2-autograding/autograded-course-starter/master/week1/homework.ipynb
Processing /Users/leah-su/Documents/github/2-autograding/autograded-course-starter/master/week-03/time-series-homework.ipynb
Processing /Users/leah-su/Documents/github/2-autograding/autograded-course-starter/master/week-04/time-series-homework-2.ipynb
Inspect `/Users/leah-su/Documents/github/2-autograding/autograded-course-starter/student/` to check it looks as you expect.
MacBook-Pro-4:autograded-course-starter leah-su$ 
```

**Comment by lwasser** [comment]
i am going to close this as these issues have all been resolved now.
