### ISSUE TITLE
`nbdistribute` when students don't accept courses

### ISSUE THREAD

**Issue by betatim** [earthlab/grading-workflow-experiments#16]
When fetching student repositories fail with a useful error message when the student repo does not exist.

**Comment by lwasser** [comment]
```
Fetching work for jlpalomino...
Traceback (most recent call last):
  File "/Users/leah-su/anaconda3/envs/earth-analytics-python/bin/nbdistribute", line 11, in <module>
    sys.exit(distribute())
  File "/Users/leah-su/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/grading/__main__.py", line 144, in distribute
    token=config['github']['token'])
  File "/Users/leah-su/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/grading/github.py", line 36, in fetch_student
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Users/leah-su/anaconda3/envs/earth-analytics-python/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://58060d2213243b43fd2f707735da1217a951fcaa@github.com/earth-analytics-edu/ea-spring-2019-jlpalomino.git']' returned non-zero exit status 128.
```
